export const shoppingItems = [
  {
    id: "1",
    name: "Wireless Mouse",
    quantity: 2,
    price: 25.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/61LtuGzXeaL._AC_SL1500_.jpg",
  },
  {
    id: "2",
    name: "Bluetooth Headphones",
    quantity: 1,
    price: 79.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/61LtuGzXeaL._AC_SL1500_.jpg",
  },
  {
    id: "9",
    name: "Cookware Set",
    quantity: 1,
    price: 129.99,
    category: "Kitchen",
    imageUrl: "https://m.media-amazon.com/images/I/61LtuGzXeaL._AC_SL1500_.jpg",
  },
  {
    id: "12",
    name: "Portable Charger",
    quantity: 2,
    price: 15.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg",
  },
  {
    id: "14",
    name: "Ballpoint Pens",
    quantity: 5,
    price: 2.49,
    category: "Stationery",
    imageUrl: "https://m.media-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg",
  },
  {
    id: "15",
    name: "LED Monitor",
    quantity: 1,
    price: 199.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg",
  },
];
